# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Intake::Models::ReviewCandidate`.
# Please instead update this file by running `bin/tapioca dsl Intake::Models::ReviewCandidate`.


class Intake::Models::ReviewCandidate
  include GeneratedAssociationMethods
  include GeneratedAttributeMethods
  extend CommonRelationMethods
  extend GeneratedRelationMethods

  private

  sig { returns(NilClass) }
  def to_ary; end

  class << self
    sig do
      params(
        attributes: T.untyped,
        block: T.nilable(T.proc.params(object: ::Intake::Models::ReviewCandidate).void)
      ).returns(::Intake::Models::ReviewCandidate)
    end
    def new(attributes = nil, &block); end
  end

  module CommonRelationMethods
    sig do
      params(
        block: T.nilable(T.proc.params(record: ::Intake::Models::ReviewCandidate).returns(T.untyped))
      ).returns(T::Boolean)
    end
    def any?(&block); end

    sig { params(column_name: T.any(String, Symbol)).returns(T.any(Integer, Float, BigDecimal)) }
    def average(column_name); end

    sig do
      params(
        block: T.nilable(T.proc.params(object: ::Intake::Models::ReviewCandidate).void)
      ).returns(::Intake::Models::ReviewCandidate)
    end
    sig do
      params(
        attributes: T::Array[T.untyped],
        block: T.nilable(T.proc.params(object: ::Intake::Models::ReviewCandidate).void)
      ).returns(T::Array[::Intake::Models::ReviewCandidate])
    end
    sig do
      params(
        attributes: T.untyped,
        block: T.nilable(T.proc.params(object: ::Intake::Models::ReviewCandidate).void)
      ).returns(::Intake::Models::ReviewCandidate)
    end
    def build(attributes = nil, &block); end

    sig { params(operation: Symbol, column_name: T.any(String, Symbol)).returns(T.any(Integer, Float, BigDecimal)) }
    def calculate(operation, column_name); end

    sig { params(column_name: T.nilable(T.any(String, Symbol))).returns(Integer) }
    sig do
      params(
        column_name: NilClass,
        block: T.proc.params(object: ::Intake::Models::ReviewCandidate).void
      ).returns(Integer)
    end
    def count(column_name = nil, &block); end

    sig do
      params(
        block: T.nilable(T.proc.params(object: ::Intake::Models::ReviewCandidate).void)
      ).returns(::Intake::Models::ReviewCandidate)
    end
    sig do
      params(
        attributes: T::Array[T.untyped],
        block: T.nilable(T.proc.params(object: ::Intake::Models::ReviewCandidate).void)
      ).returns(T::Array[::Intake::Models::ReviewCandidate])
    end
    sig do
      params(
        attributes: T.untyped,
        block: T.nilable(T.proc.params(object: ::Intake::Models::ReviewCandidate).void)
      ).returns(::Intake::Models::ReviewCandidate)
    end
    def create(attributes = nil, &block); end

    sig do
      params(
        block: T.nilable(T.proc.params(object: ::Intake::Models::ReviewCandidate).void)
      ).returns(::Intake::Models::ReviewCandidate)
    end
    sig do
      params(
        attributes: T::Array[T.untyped],
        block: T.nilable(T.proc.params(object: ::Intake::Models::ReviewCandidate).void)
      ).returns(T::Array[::Intake::Models::ReviewCandidate])
    end
    sig do
      params(
        attributes: T.untyped,
        block: T.nilable(T.proc.params(object: ::Intake::Models::ReviewCandidate).void)
      ).returns(::Intake::Models::ReviewCandidate)
    end
    def create!(attributes = nil, &block); end

    sig do
      params(
        attributes: T::Array[T.untyped],
        block: T.nilable(T.proc.params(object: ::Intake::Models::ReviewCandidate).void)
      ).returns(T::Array[::Intake::Models::ReviewCandidate])
    end
    sig do
      params(
        attributes: T.untyped,
        block: T.nilable(T.proc.params(object: ::Intake::Models::ReviewCandidate).void)
      ).returns(::Intake::Models::ReviewCandidate)
    end
    def create_or_find_by(attributes, &block); end

    sig do
      params(
        attributes: T::Array[T.untyped],
        block: T.nilable(T.proc.params(object: ::Intake::Models::ReviewCandidate).void)
      ).returns(T::Array[::Intake::Models::ReviewCandidate])
    end
    sig do
      params(
        attributes: T.untyped,
        block: T.nilable(T.proc.params(object: ::Intake::Models::ReviewCandidate).void)
      ).returns(::Intake::Models::ReviewCandidate)
    end
    def create_or_find_by!(attributes, &block); end

    sig do
      params(
        records: T.any(::Intake::Models::ReviewCandidate, Integer, String, T::Enumerable[T.any(::Intake::Models::ReviewCandidate, Integer, String, T::Enumerable[::Intake::Models::ReviewCandidate])])
      ).returns(Integer)
    end
    def delete(*records); end

    sig { returns(Integer) }
    def delete_all; end

    sig { params(args: T.untyped).returns(Integer) }
    def delete_by(*args); end

    sig do
      params(
        records: T.any(::Intake::Models::ReviewCandidate, Integer, String, T::Enumerable[T.any(::Intake::Models::ReviewCandidate, Integer, String, T::Enumerable[::Intake::Models::ReviewCandidate])])
      ).returns(T::Array[::Intake::Models::ReviewCandidate])
    end
    def destroy(*records); end

    sig { returns(T::Array[::Intake::Models::ReviewCandidate]) }
    def destroy_all; end

    sig { returns(T::Array[::Intake::Models::ReviewCandidate]) }
    def destroy_all; end

    sig { params(args: T.untyped).returns(T::Array[::Intake::Models::ReviewCandidate]) }
    def destroy_by(*args); end

    sig { params(conditions: T.untyped).returns(T::Boolean) }
    def exists?(conditions = :none); end

    sig { returns(T.nilable(::Intake::Models::ReviewCandidate)) }
    def fifth; end

    sig { returns(::Intake::Models::ReviewCandidate) }
    def fifth!; end

    sig do
      params(
        args: T.any(String, Symbol, ::ActiveSupport::Multibyte::Chars, T::Boolean, BigDecimal, Numeric, ::ActiveRecord::Type::Binary::Data, ::ActiveRecord::Type::Time::Value, Date, Time, ::ActiveSupport::Duration, T::Class[T.anything])
      ).returns(::Intake::Models::ReviewCandidate)
    end
    sig do
      params(
        args: T::Array[T.any(String, Symbol, ::ActiveSupport::Multibyte::Chars, T::Boolean, BigDecimal, Numeric, ::ActiveRecord::Type::Binary::Data, ::ActiveRecord::Type::Time::Value, Date, Time, ::ActiveSupport::Duration, T::Class[T.anything])]
      ).returns(T::Enumerable[::Intake::Models::ReviewCandidate])
    end
    sig do
      params(
        args: NilClass,
        block: T.proc.params(object: ::Intake::Models::ReviewCandidate).void
      ).returns(T.nilable(::Intake::Models::ReviewCandidate))
    end
    def find(args = nil, &block); end

    sig { params(args: T.untyped).returns(T.nilable(::Intake::Models::ReviewCandidate)) }
    def find_by(*args); end

    sig { params(args: T.untyped).returns(::Intake::Models::ReviewCandidate) }
    def find_by!(*args); end

    sig do
      params(
        start: T.untyped,
        finish: T.untyped,
        batch_size: Integer,
        error_on_ignore: T.untyped,
        cursor: T.untyped,
        order: T.any(Symbol, T::Array[Symbol]),
        block: T.proc.params(object: ::Intake::Models::ReviewCandidate).void
      ).void
    end
    sig do
      params(
        start: T.untyped,
        finish: T.untyped,
        batch_size: Integer,
        error_on_ignore: T.untyped,
        cursor: T.untyped,
        order: T.any(Symbol, T::Array[Symbol])
      ).returns(T::Enumerator[::Intake::Models::ReviewCandidate])
    end
    def find_each(start: nil, finish: nil, batch_size: 1000, error_on_ignore: nil, cursor: primary_key, order: :asc, &block); end

    sig do
      params(
        start: T.untyped,
        finish: T.untyped,
        batch_size: Integer,
        error_on_ignore: T.untyped,
        cursor: T.untyped,
        order: T.any(Symbol, T::Array[Symbol]),
        block: T.proc.params(object: T::Array[::Intake::Models::ReviewCandidate]).void
      ).void
    end
    sig do
      params(
        start: T.untyped,
        finish: T.untyped,
        batch_size: Integer,
        error_on_ignore: T.untyped,
        cursor: T.untyped,
        order: T.any(Symbol, T::Array[Symbol])
      ).returns(T::Enumerator[T::Array[::Intake::Models::ReviewCandidate]])
    end
    def find_in_batches(start: nil, finish: nil, batch_size: 1000, error_on_ignore: nil, cursor: primary_key, order: :asc, &block); end

    sig do
      params(
        attributes: T::Array[T.untyped],
        block: T.nilable(T.proc.params(object: ::Intake::Models::ReviewCandidate).void)
      ).returns(T::Array[::Intake::Models::ReviewCandidate])
    end
    sig do
      params(
        attributes: T.untyped,
        block: T.nilable(T.proc.params(object: ::Intake::Models::ReviewCandidate).void)
      ).returns(::Intake::Models::ReviewCandidate)
    end
    def find_or_create_by(attributes, &block); end

    sig do
      params(
        attributes: T::Array[T.untyped],
        block: T.nilable(T.proc.params(object: ::Intake::Models::ReviewCandidate).void)
      ).returns(T::Array[::Intake::Models::ReviewCandidate])
    end
    sig do
      params(
        attributes: T.untyped,
        block: T.nilable(T.proc.params(object: ::Intake::Models::ReviewCandidate).void)
      ).returns(::Intake::Models::ReviewCandidate)
    end
    def find_or_create_by!(attributes, &block); end

    sig do
      params(
        attributes: T::Array[T.untyped],
        block: T.nilable(T.proc.params(object: ::Intake::Models::ReviewCandidate).void)
      ).returns(T::Array[::Intake::Models::ReviewCandidate])
    end
    sig do
      params(
        attributes: T.untyped,
        block: T.nilable(T.proc.params(object: ::Intake::Models::ReviewCandidate).void)
      ).returns(::Intake::Models::ReviewCandidate)
    end
    def find_or_initialize_by(attributes, &block); end

    sig { params(signed_id: T.untyped, purpose: T.untyped).returns(T.nilable(::Intake::Models::ReviewCandidate)) }
    def find_signed(signed_id, purpose: nil); end

    sig { params(signed_id: T.untyped, purpose: T.untyped).returns(::Intake::Models::ReviewCandidate) }
    def find_signed!(signed_id, purpose: nil); end

    sig { params(arg: T.untyped, args: T.untyped).returns(::Intake::Models::ReviewCandidate) }
    def find_sole_by(arg, *args); end

    sig { returns(T.nilable(::Intake::Models::ReviewCandidate)) }
    sig { params(limit: Integer).returns(T::Array[::Intake::Models::ReviewCandidate]) }
    def first(limit = nil); end

    sig { returns(::Intake::Models::ReviewCandidate) }
    def first!; end

    sig { returns(T.nilable(::Intake::Models::ReviewCandidate)) }
    def forty_two; end

    sig { returns(::Intake::Models::ReviewCandidate) }
    def forty_two!; end

    sig { returns(T.nilable(::Intake::Models::ReviewCandidate)) }
    def fourth; end

    sig { returns(::Intake::Models::ReviewCandidate) }
    def fourth!; end

    sig { returns(T::Array[::Integer]) }
    def ids; end

    sig do
      params(
        of: Integer,
        start: T.untyped,
        finish: T.untyped,
        load: T.untyped,
        error_on_ignore: T.untyped,
        cursor: T.untyped,
        order: T.any(Symbol, T::Array[Symbol]),
        use_ranges: T.untyped,
        block: T.proc.params(object: PrivateRelation).void
      ).void
    end
    sig do
      params(
        of: Integer,
        start: T.untyped,
        finish: T.untyped,
        load: T.untyped,
        error_on_ignore: T.untyped,
        cursor: T.untyped,
        order: T.any(Symbol, T::Array[Symbol]),
        use_ranges: T.untyped
      ).returns(::ActiveRecord::Batches::BatchEnumerator)
    end
    def in_batches(of: 1000, start: nil, finish: nil, load: false, error_on_ignore: nil, cursor: primary_key, order: :asc, use_ranges: nil, &block); end

    sig { params(record: T.untyped).returns(T::Boolean) }
    def include?(record); end

    sig { returns(T.nilable(::Intake::Models::ReviewCandidate)) }
    sig { params(limit: Integer).returns(T::Array[::Intake::Models::ReviewCandidate]) }
    def last(limit = nil); end

    sig { returns(::Intake::Models::ReviewCandidate) }
    def last!; end

    sig do
      params(
        block: T.nilable(T.proc.params(record: ::Intake::Models::ReviewCandidate).returns(T.untyped))
      ).returns(T::Boolean)
    end
    def many?(&block); end

    sig { params(column_name: T.any(String, Symbol)).returns(T.untyped) }
    def maximum(column_name); end

    sig { params(record: T.untyped).returns(T::Boolean) }
    def member?(record); end

    sig { params(column_name: T.any(String, Symbol)).returns(T.untyped) }
    def minimum(column_name); end

    sig do
      params(
        block: T.nilable(T.proc.params(object: ::Intake::Models::ReviewCandidate).void)
      ).returns(::Intake::Models::ReviewCandidate)
    end
    sig do
      params(
        attributes: T::Array[T.untyped],
        block: T.nilable(T.proc.params(object: ::Intake::Models::ReviewCandidate).void)
      ).returns(T::Array[::Intake::Models::ReviewCandidate])
    end
    sig do
      params(
        attributes: T.untyped,
        block: T.nilable(T.proc.params(object: ::Intake::Models::ReviewCandidate).void)
      ).returns(::Intake::Models::ReviewCandidate)
    end
    def new(attributes = nil, &block); end

    sig do
      params(
        block: T.nilable(T.proc.params(record: ::Intake::Models::ReviewCandidate).returns(T.untyped))
      ).returns(T::Boolean)
    end
    def none?(&block); end

    sig do
      params(
        block: T.nilable(T.proc.params(record: ::Intake::Models::ReviewCandidate).returns(T.untyped))
      ).returns(T::Boolean)
    end
    def one?(&block); end

    sig { params(column_names: T.untyped).returns(T.untyped) }
    def pick(*column_names); end

    sig { params(column_names: T.untyped).returns(T.untyped) }
    def pluck(*column_names); end

    sig { returns(T.nilable(::Intake::Models::ReviewCandidate)) }
    def second; end

    sig { returns(::Intake::Models::ReviewCandidate) }
    def second!; end

    sig { returns(T.nilable(::Intake::Models::ReviewCandidate)) }
    def second_to_last; end

    sig { returns(::Intake::Models::ReviewCandidate) }
    def second_to_last!; end

    sig { returns(::Intake::Models::ReviewCandidate) }
    def sole; end

    sig { params(initial_value_or_column: T.untyped).returns(T.any(Integer, Float, BigDecimal)) }
    sig do
      type_parameters(:U)
        .params(
          initial_value_or_column: T.nilable(T.type_parameter(:U)),
          block: T.proc.params(object: ::Intake::Models::ReviewCandidate).returns(T.type_parameter(:U))
        ).returns(T.type_parameter(:U))
    end
    def sum(initial_value_or_column = nil, &block); end

    sig { returns(T.nilable(::Intake::Models::ReviewCandidate)) }
    sig { params(limit: Integer).returns(T::Array[::Intake::Models::ReviewCandidate]) }
    def take(limit = nil); end

    sig { returns(::Intake::Models::ReviewCandidate) }
    def take!; end

    sig { returns(T.nilable(::Intake::Models::ReviewCandidate)) }
    def third; end

    sig { returns(::Intake::Models::ReviewCandidate) }
    def third!; end

    sig { returns(T.nilable(::Intake::Models::ReviewCandidate)) }
    def third_to_last; end

    sig { returns(::Intake::Models::ReviewCandidate) }
    def third_to_last!; end
  end

  module GeneratedAssociationMethods
    sig { params(args: T.untyped, blk: T.untyped).returns(::Intake::Models::ReviewCase) }
    def build_review_case(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(::Intake::Models::ReviewRejection) }
    def build_review_rejection(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(::Intake::Models::ReviewCase) }
    def create_review_case(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(::Intake::Models::ReviewCase) }
    def create_review_case!(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(::Intake::Models::ReviewRejection) }
    def create_review_rejection(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(::Intake::Models::ReviewRejection) }
    def create_review_rejection!(*args, &blk); end

    sig { returns(T.nilable(::Intake::Models::ReviewCase)) }
    def reload_review_case; end

    sig { returns(T.nilable(::Intake::Models::ReviewRejection)) }
    def reload_review_rejection; end

    sig { void }
    def reset_review_case; end

    sig { void }
    def reset_review_rejection; end

    sig { returns(T.nilable(::Intake::Models::ReviewCase)) }
    def review_case; end

    sig { params(value: T.nilable(::Intake::Models::ReviewCase)).void }
    def review_case=(value); end

    sig { returns(T::Boolean) }
    def review_case_changed?; end

    sig { returns(T::Boolean) }
    def review_case_previously_changed?; end

    sig { returns(T.nilable(::Intake::Models::ReviewRejection)) }
    def review_rejection; end

    sig { params(value: T.nilable(::Intake::Models::ReviewRejection)).void }
    def review_rejection=(value); end
  end

  module GeneratedAssociationRelationMethods
    sig { returns(PrivateAssociationRelation) }
    def all; end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def and(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def annotate(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def arel_columns(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def create_with(*args, &blk); end

    sig { params(value: T::Boolean).returns(PrivateAssociationRelation) }
    def distinct(value = true); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def eager_load(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def except(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def excluding(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def extending(*args, &blk); end

    sig { params(association: Symbol).returns(T::Array[T.untyped]) }
    def extract_associated(association); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def from(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelationGroupChain) }
    def group(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def having(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def in_order_of(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def includes(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def invert_where(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def joins(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def left_joins(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def left_outer_joins(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def limit(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def lock(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def merge(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def none(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def null_relation?(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def offset(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def only(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def optimizer_hints(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def or(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def order(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def preload(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def readonly(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def references(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def regroup(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def reorder(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def reselect(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def reverse_order(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def rewhere(*args, &blk); end

    sig { params(args: T.untyped).returns(PrivateAssociationRelation) }
    sig do
      params(
        blk: T.proc.params(record: ::Intake::Models::ReviewCandidate).returns(BasicObject)
      ).returns(T::Array[::Intake::Models::ReviewCandidate])
    end
    def select(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def strict_loading(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def structurally_compatible?(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def uniq!(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def unscope(*args, &blk); end

    sig { returns(PrivateAssociationRelation) }
    sig { type_parameters(:U).params(block: T.proc.returns(T.type_parameter(:U))).returns(T.type_parameter(:U)) }
    def unscoped(&block); end

    sig { returns(PrivateAssociationRelationWhereChain) }
    sig { params(args: T.untyped).returns(PrivateAssociationRelation) }
    def where(*args); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def with(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def with_recursive(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def without(*args, &blk); end
  end

  module GeneratedAttributeMethods
    sig { returns(T.untyped) }
    def comparison; end

    sig { params(value: T.untyped).returns(T.untyped) }
    def comparison=(value); end

    sig { returns(T::Boolean) }
    def comparison?; end

    sig { returns(T.untyped) }
    def comparison_before_last_save; end

    sig { returns(T.untyped) }
    def comparison_before_type_cast; end

    sig { returns(T::Boolean) }
    def comparison_came_from_user?; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def comparison_change; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def comparison_change_to_be_saved; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def comparison_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.untyped) }
    def comparison_in_database; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def comparison_previous_change; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def comparison_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.untyped) }
    def comparison_previously_was; end

    sig { returns(T.untyped) }
    def comparison_was; end

    sig { void }
    def comparison_will_change!; end

    sig { returns(T.untyped) }
    def conflicting_association; end

    sig { params(value: T.untyped).returns(T.untyped) }
    def conflicting_association=(value); end

    sig { returns(T::Boolean) }
    def conflicting_association?; end

    sig { returns(T.untyped) }
    def conflicting_association_before_last_save; end

    sig { returns(T.untyped) }
    def conflicting_association_before_type_cast; end

    sig { returns(T::Boolean) }
    def conflicting_association_came_from_user?; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def conflicting_association_change; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def conflicting_association_change_to_be_saved; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def conflicting_association_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.untyped) }
    def conflicting_association_in_database; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def conflicting_association_previous_change; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def conflicting_association_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.untyped) }
    def conflicting_association_previously_was; end

    sig { returns(T.untyped) }
    def conflicting_association_was; end

    sig { void }
    def conflicting_association_will_change!; end

    sig { returns(::ActiveSupport::TimeWithZone) }
    def created_at; end

    sig { params(value: ::ActiveSupport::TimeWithZone).returns(::ActiveSupport::TimeWithZone) }
    def created_at=(value); end

    sig { returns(T::Boolean) }
    def created_at?; end

    sig { returns(T.nilable(::ActiveSupport::TimeWithZone)) }
    def created_at_before_last_save; end

    sig { returns(T.untyped) }
    def created_at_before_type_cast; end

    sig { returns(T::Boolean) }
    def created_at_came_from_user?; end

    sig { returns(T.nilable([::ActiveSupport::TimeWithZone, ::ActiveSupport::TimeWithZone])) }
    def created_at_change; end

    sig { returns(T.nilable([::ActiveSupport::TimeWithZone, ::ActiveSupport::TimeWithZone])) }
    def created_at_change_to_be_saved; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def created_at_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::ActiveSupport::TimeWithZone)) }
    def created_at_in_database; end

    sig { returns(T.nilable([::ActiveSupport::TimeWithZone, ::ActiveSupport::TimeWithZone])) }
    def created_at_previous_change; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def created_at_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::ActiveSupport::TimeWithZone)) }
    def created_at_previously_was; end

    sig { returns(T.nilable(::ActiveSupport::TimeWithZone)) }
    def created_at_was; end

    sig { void }
    def created_at_will_change!; end

    sig { returns(T.untyped) }
    def differing_fields; end

    sig { params(value: T.untyped).returns(T.untyped) }
    def differing_fields=(value); end

    sig { returns(T::Boolean) }
    def differing_fields?; end

    sig { returns(T.untyped) }
    def differing_fields_before_last_save; end

    sig { returns(T.untyped) }
    def differing_fields_before_type_cast; end

    sig { returns(T::Boolean) }
    def differing_fields_came_from_user?; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def differing_fields_change; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def differing_fields_change_to_be_saved; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def differing_fields_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.untyped) }
    def differing_fields_in_database; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def differing_fields_previous_change; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def differing_fields_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.untyped) }
    def differing_fields_previously_was; end

    sig { returns(T.untyped) }
    def differing_fields_was; end

    sig { void }
    def differing_fields_will_change!; end

    sig { returns(::Integer) }
    def evidence_revision; end

    sig { params(value: ::Integer).returns(::Integer) }
    def evidence_revision=(value); end

    sig { returns(T::Boolean) }
    def evidence_revision?; end

    sig { returns(T.nilable(::Integer)) }
    def evidence_revision_before_last_save; end

    sig { returns(T.untyped) }
    def evidence_revision_before_type_cast; end

    sig { returns(T::Boolean) }
    def evidence_revision_came_from_user?; end

    sig { returns(T.nilable([::Integer, ::Integer])) }
    def evidence_revision_change; end

    sig { returns(T.nilable([::Integer, ::Integer])) }
    def evidence_revision_change_to_be_saved; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def evidence_revision_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::Integer)) }
    def evidence_revision_in_database; end

    sig { returns(T.nilable([::Integer, ::Integer])) }
    def evidence_revision_previous_change; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def evidence_revision_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::Integer)) }
    def evidence_revision_previously_was; end

    sig { returns(T.nilable(::Integer)) }
    def evidence_revision_was; end

    sig { void }
    def evidence_revision_will_change!; end

    sig { returns(::Integer) }
    def id; end

    sig { params(value: ::Integer).returns(::Integer) }
    def id=(value); end

    sig { returns(T::Boolean) }
    def id?; end

    sig { returns(T.nilable(::Integer)) }
    def id_before_last_save; end

    sig { returns(T.untyped) }
    def id_before_type_cast; end

    sig { returns(T::Boolean) }
    def id_came_from_user?; end

    sig { returns(T.nilable([::Integer, ::Integer])) }
    def id_change; end

    sig { returns(T.nilable([::Integer, ::Integer])) }
    def id_change_to_be_saved; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def id_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::Integer)) }
    def id_in_database; end

    sig { returns(T.nilable([::Integer, ::Integer])) }
    def id_previous_change; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def id_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::Integer)) }
    def id_previously_was; end

    sig { returns(::Integer) }
    def id_value; end

    sig { params(value: ::Integer).returns(::Integer) }
    def id_value=(value); end

    sig { returns(T::Boolean) }
    def id_value?; end

    sig { returns(T.nilable(::Integer)) }
    def id_value_before_last_save; end

    sig { returns(T.untyped) }
    def id_value_before_type_cast; end

    sig { returns(T::Boolean) }
    def id_value_came_from_user?; end

    sig { returns(T.nilable([::Integer, ::Integer])) }
    def id_value_change; end

    sig { returns(T.nilable([::Integer, ::Integer])) }
    def id_value_change_to_be_saved; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def id_value_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::Integer)) }
    def id_value_in_database; end

    sig { returns(T.nilable([::Integer, ::Integer])) }
    def id_value_previous_change; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def id_value_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::Integer)) }
    def id_value_previously_was; end

    sig { returns(T.nilable(::Integer)) }
    def id_value_was; end

    sig { void }
    def id_value_will_change!; end

    sig { returns(T.nilable(::Integer)) }
    def id_was; end

    sig { void }
    def id_will_change!; end

    sig { returns(T.untyped) }
    def original; end

    sig { params(value: T.untyped).returns(T.untyped) }
    def original=(value); end

    sig { returns(T::Boolean) }
    def original?; end

    sig { returns(T.untyped) }
    def original_before_last_save; end

    sig { returns(T.untyped) }
    def original_before_type_cast; end

    sig { returns(T::Boolean) }
    def original_came_from_user?; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def original_change; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def original_change_to_be_saved; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def original_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.untyped) }
    def original_in_database; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def original_previous_change; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def original_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.untyped) }
    def original_previously_was; end

    sig { returns(T.untyped) }
    def original_was; end

    sig { void }
    def original_will_change!; end

    sig { returns(::Integer) }
    def product_id; end

    sig { params(value: ::Integer).returns(::Integer) }
    def product_id=(value); end

    sig { returns(T::Boolean) }
    def product_id?; end

    sig { returns(T.nilable(::Integer)) }
    def product_id_before_last_save; end

    sig { returns(T.untyped) }
    def product_id_before_type_cast; end

    sig { returns(T::Boolean) }
    def product_id_came_from_user?; end

    sig { returns(T.nilable([::Integer, ::Integer])) }
    def product_id_change; end

    sig { returns(T.nilable([::Integer, ::Integer])) }
    def product_id_change_to_be_saved; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def product_id_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::Integer)) }
    def product_id_in_database; end

    sig { returns(T.nilable([::Integer, ::Integer])) }
    def product_id_previous_change; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def product_id_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::Integer)) }
    def product_id_previously_was; end

    sig { returns(T.nilable(::Integer)) }
    def product_id_was; end

    sig { void }
    def product_id_will_change!; end

    sig { returns(::Integer) }
    def rank; end

    sig { params(value: ::Integer).returns(::Integer) }
    def rank=(value); end

    sig { returns(T::Boolean) }
    def rank?; end

    sig { returns(T.nilable(::Integer)) }
    def rank_before_last_save; end

    sig { returns(T.untyped) }
    def rank_before_type_cast; end

    sig { returns(T::Boolean) }
    def rank_came_from_user?; end

    sig { returns(T.nilable([::Integer, ::Integer])) }
    def rank_change; end

    sig { returns(T.nilable([::Integer, ::Integer])) }
    def rank_change_to_be_saved; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def rank_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::Integer)) }
    def rank_in_database; end

    sig { returns(T.nilable([::Integer, ::Integer])) }
    def rank_previous_change; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def rank_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::Integer)) }
    def rank_previously_was; end

    sig { returns(T.nilable(::Integer)) }
    def rank_was; end

    sig { void }
    def rank_will_change!; end

    sig { void }
    def restore_comparison!; end

    sig { void }
    def restore_conflicting_association!; end

    sig { void }
    def restore_created_at!; end

    sig { void }
    def restore_differing_fields!; end

    sig { void }
    def restore_evidence_revision!; end

    sig { void }
    def restore_id!; end

    sig { void }
    def restore_id_value!; end

    sig { void }
    def restore_original!; end

    sig { void }
    def restore_product_id!; end

    sig { void }
    def restore_rank!; end

    sig { void }
    def restore_review_case_id!; end

    sig { void }
    def restore_score!; end

    sig { returns(::Integer) }
    def review_case_id; end

    sig { params(value: ::Integer).returns(::Integer) }
    def review_case_id=(value); end

    sig { returns(T::Boolean) }
    def review_case_id?; end

    sig { returns(T.nilable(::Integer)) }
    def review_case_id_before_last_save; end

    sig { returns(T.untyped) }
    def review_case_id_before_type_cast; end

    sig { returns(T::Boolean) }
    def review_case_id_came_from_user?; end

    sig { returns(T.nilable([::Integer, ::Integer])) }
    def review_case_id_change; end

    sig { returns(T.nilable([::Integer, ::Integer])) }
    def review_case_id_change_to_be_saved; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def review_case_id_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::Integer)) }
    def review_case_id_in_database; end

    sig { returns(T.nilable([::Integer, ::Integer])) }
    def review_case_id_previous_change; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def review_case_id_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::Integer)) }
    def review_case_id_previously_was; end

    sig { returns(T.nilable(::Integer)) }
    def review_case_id_was; end

    sig { void }
    def review_case_id_will_change!; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def saved_change_to_comparison; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def saved_change_to_comparison?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def saved_change_to_conflicting_association; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def saved_change_to_conflicting_association?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable([::ActiveSupport::TimeWithZone, ::ActiveSupport::TimeWithZone])) }
    def saved_change_to_created_at; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def saved_change_to_created_at?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def saved_change_to_differing_fields; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def saved_change_to_differing_fields?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable([::Integer, ::Integer])) }
    def saved_change_to_evidence_revision; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def saved_change_to_evidence_revision?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable([::Integer, ::Integer])) }
    def saved_change_to_id; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def saved_change_to_id?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable([::Integer, ::Integer])) }
    def saved_change_to_id_value; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def saved_change_to_id_value?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def saved_change_to_original; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def saved_change_to_original?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable([::Integer, ::Integer])) }
    def saved_change_to_product_id; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def saved_change_to_product_id?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable([::Integer, ::Integer])) }
    def saved_change_to_rank; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def saved_change_to_rank?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable([::Integer, ::Integer])) }
    def saved_change_to_review_case_id; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def saved_change_to_review_case_id?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable([::BigDecimal, ::BigDecimal])) }
    def saved_change_to_score; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def saved_change_to_score?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(::BigDecimal) }
    def score; end

    sig { params(value: ::BigDecimal).returns(::BigDecimal) }
    def score=(value); end

    sig { returns(T::Boolean) }
    def score?; end

    sig { returns(T.nilable(::BigDecimal)) }
    def score_before_last_save; end

    sig { returns(T.untyped) }
    def score_before_type_cast; end

    sig { returns(T::Boolean) }
    def score_came_from_user?; end

    sig { returns(T.nilable([::BigDecimal, ::BigDecimal])) }
    def score_change; end

    sig { returns(T.nilable([::BigDecimal, ::BigDecimal])) }
    def score_change_to_be_saved; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def score_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::BigDecimal)) }
    def score_in_database; end

    sig { returns(T.nilable([::BigDecimal, ::BigDecimal])) }
    def score_previous_change; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def score_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::BigDecimal)) }
    def score_previously_was; end

    sig { returns(T.nilable(::BigDecimal)) }
    def score_was; end

    sig { void }
    def score_will_change!; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def will_save_change_to_comparison?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def will_save_change_to_conflicting_association?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def will_save_change_to_created_at?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def will_save_change_to_differing_fields?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def will_save_change_to_evidence_revision?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def will_save_change_to_id?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def will_save_change_to_id_value?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def will_save_change_to_original?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def will_save_change_to_product_id?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def will_save_change_to_rank?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def will_save_change_to_review_case_id?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def will_save_change_to_score?(from: T.unsafe(nil), to: T.unsafe(nil)); end
  end

  module GeneratedRelationMethods
    sig { returns(PrivateRelation) }
    def all; end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def and(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def annotate(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def arel_columns(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def create_with(*args, &blk); end

    sig { params(value: T::Boolean).returns(PrivateRelation) }
    def distinct(value = true); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def eager_load(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def except(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def excluding(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def extending(*args, &blk); end

    sig { params(association: Symbol).returns(T::Array[T.untyped]) }
    def extract_associated(association); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def from(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelationGroupChain) }
    def group(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def having(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def in_order_of(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def includes(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def invert_where(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def joins(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def left_joins(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def left_outer_joins(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def limit(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def lock(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def merge(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def none(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def null_relation?(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def offset(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def only(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def optimizer_hints(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def or(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def order(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def preload(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def readonly(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def references(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def regroup(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def reorder(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def reselect(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def reverse_order(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def rewhere(*args, &blk); end

    sig { params(args: T.untyped).returns(PrivateRelation) }
    sig do
      params(
        blk: T.proc.params(record: ::Intake::Models::ReviewCandidate).returns(BasicObject)
      ).returns(T::Array[::Intake::Models::ReviewCandidate])
    end
    def select(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def strict_loading(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def structurally_compatible?(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def uniq!(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def unscope(*args, &blk); end

    sig { returns(PrivateRelation) }
    sig { type_parameters(:U).params(block: T.proc.returns(T.type_parameter(:U))).returns(T.type_parameter(:U)) }
    def unscoped(&block); end

    sig { returns(PrivateRelationWhereChain) }
    sig { params(args: T.untyped).returns(PrivateRelation) }
    def where(*args); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def with(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def with_recursive(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def without(*args, &blk); end
  end

  class PrivateAssociationRelation < ::ActiveRecord::AssociationRelation
    include CommonRelationMethods
    include GeneratedAssociationRelationMethods

    Elem = type_member { { fixed: ::Intake::Models::ReviewCandidate } }

    sig { returns(T::Array[::Intake::Models::ReviewCandidate]) }
    def to_a; end

    sig { returns(T::Array[::Intake::Models::ReviewCandidate]) }
    def to_ary; end
  end

  class PrivateAssociationRelationGroupChain < PrivateAssociationRelation
    Elem = type_member { { fixed: ::Intake::Models::ReviewCandidate } }

    sig { params(column_name: T.any(String, Symbol)).returns(T::Hash[T.untyped, T.any(Integer, Float, BigDecimal)]) }
    def average(column_name); end

    sig do
      params(
        operation: Symbol,
        column_name: T.any(String, Symbol)
      ).returns(T::Hash[T.untyped, T.any(Integer, Float, BigDecimal)])
    end
    def calculate(operation, column_name); end

    sig { params(column_name: T.untyped).returns(T::Hash[T.untyped, Integer]) }
    def count(column_name = nil); end

    sig { params(args: T.untyped, blk: T.untyped).returns(T.self_type) }
    def having(*args, &blk); end

    sig { params(column_name: T.any(String, Symbol)).returns(T::Hash[T.untyped, T.untyped]) }
    def maximum(column_name); end

    sig { params(column_name: T.any(String, Symbol)).returns(T::Hash[T.untyped, T.untyped]) }
    def minimum(column_name); end

    sig { returns(T::Hash[T.untyped, Integer]) }
    def size; end

    sig do
      params(
        column_name: T.nilable(T.any(String, Symbol)),
        block: T.nilable(T.proc.params(record: T.untyped).returns(T.untyped))
      ).returns(T::Hash[T.untyped, T.any(Integer, Float, BigDecimal)])
    end
    def sum(column_name = nil, &block); end
  end

  class PrivateAssociationRelationWhereChain
    Elem = type_member { { fixed: ::Intake::Models::ReviewCandidate } }

    sig { params(args: T.untyped).returns(PrivateAssociationRelation) }
    def associated(*args); end

    sig { params(args: T.untyped).returns(PrivateAssociationRelation) }
    def missing(*args); end

    sig { params(opts: T.untyped, rest: T.untyped).returns(PrivateAssociationRelation) }
    def not(opts, *rest); end
  end

  class PrivateCollectionProxy < ::ActiveRecord::Associations::CollectionProxy
    include CommonRelationMethods
    include GeneratedAssociationRelationMethods

    Elem = type_member { { fixed: ::Intake::Models::ReviewCandidate } }

    sig do
      params(
        records: T.any(::Intake::Models::ReviewCandidate, T::Enumerable[T.any(::Intake::Models::ReviewCandidate, T::Enumerable[::Intake::Models::ReviewCandidate])])
      ).returns(PrivateCollectionProxy)
    end
    def <<(*records); end

    sig do
      params(
        records: T.any(::Intake::Models::ReviewCandidate, T::Enumerable[T.any(::Intake::Models::ReviewCandidate, T::Enumerable[::Intake::Models::ReviewCandidate])])
      ).returns(PrivateCollectionProxy)
    end
    def append(*records); end

    sig { returns(PrivateCollectionProxy) }
    def clear; end

    sig do
      params(
        records: T.any(::Intake::Models::ReviewCandidate, T::Enumerable[T.any(::Intake::Models::ReviewCandidate, T::Enumerable[::Intake::Models::ReviewCandidate])])
      ).returns(PrivateCollectionProxy)
    end
    def concat(*records); end

    sig { returns(T::Array[::Intake::Models::ReviewCandidate]) }
    def load_target; end

    sig do
      params(
        records: T.any(::Intake::Models::ReviewCandidate, T::Enumerable[T.any(::Intake::Models::ReviewCandidate, T::Enumerable[::Intake::Models::ReviewCandidate])])
      ).returns(PrivateCollectionProxy)
    end
    def prepend(*records); end

    sig do
      params(
        records: T.any(::Intake::Models::ReviewCandidate, T::Enumerable[T.any(::Intake::Models::ReviewCandidate, T::Enumerable[::Intake::Models::ReviewCandidate])])
      ).returns(PrivateCollectionProxy)
    end
    def push(*records); end

    sig do
      params(
        other_array: T.any(::Intake::Models::ReviewCandidate, T::Enumerable[T.any(::Intake::Models::ReviewCandidate, T::Enumerable[::Intake::Models::ReviewCandidate])])
      ).returns(T::Array[::Intake::Models::ReviewCandidate])
    end
    def replace(other_array); end

    sig { returns(PrivateAssociationRelation) }
    def scope; end

    sig { returns(T::Array[::Intake::Models::ReviewCandidate]) }
    def target; end

    sig { returns(T::Array[::Intake::Models::ReviewCandidate]) }
    def to_a; end

    sig { returns(T::Array[::Intake::Models::ReviewCandidate]) }
    def to_ary; end
  end

  class PrivateRelation < ::ActiveRecord::Relation
    include CommonRelationMethods
    include GeneratedRelationMethods

    Elem = type_member { { fixed: ::Intake::Models::ReviewCandidate } }

    sig { returns(T::Array[::Intake::Models::ReviewCandidate]) }
    def to_a; end

    sig { returns(T::Array[::Intake::Models::ReviewCandidate]) }
    def to_ary; end
  end

  class PrivateRelationGroupChain < PrivateRelation
    Elem = type_member { { fixed: ::Intake::Models::ReviewCandidate } }

    sig { params(column_name: T.any(String, Symbol)).returns(T::Hash[T.untyped, T.any(Integer, Float, BigDecimal)]) }
    def average(column_name); end

    sig do
      params(
        operation: Symbol,
        column_name: T.any(String, Symbol)
      ).returns(T::Hash[T.untyped, T.any(Integer, Float, BigDecimal)])
    end
    def calculate(operation, column_name); end

    sig { params(column_name: T.untyped).returns(T::Hash[T.untyped, Integer]) }
    def count(column_name = nil); end

    sig { params(args: T.untyped, blk: T.untyped).returns(T.self_type) }
    def having(*args, &blk); end

    sig { params(column_name: T.any(String, Symbol)).returns(T::Hash[T.untyped, T.untyped]) }
    def maximum(column_name); end

    sig { params(column_name: T.any(String, Symbol)).returns(T::Hash[T.untyped, T.untyped]) }
    def minimum(column_name); end

    sig { returns(T::Hash[T.untyped, Integer]) }
    def size; end

    sig do
      params(
        column_name: T.nilable(T.any(String, Symbol)),
        block: T.nilable(T.proc.params(record: T.untyped).returns(T.untyped))
      ).returns(T::Hash[T.untyped, T.any(Integer, Float, BigDecimal)])
    end
    def sum(column_name = nil, &block); end
  end

  class PrivateRelationWhereChain
    Elem = type_member { { fixed: ::Intake::Models::ReviewCandidate } }

    sig { params(args: T.untyped).returns(PrivateRelation) }
    def associated(*args); end

    sig { params(args: T.untyped).returns(PrivateRelation) }
    def missing(*args); end

    sig { params(opts: T.untyped, rest: T.untyped).returns(PrivateRelation) }
    def not(opts, *rest); end
  end
end
